# BASIC TENSORFLOW

# LOAD PACKAGES

In [7]:
import numpy as np
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()
print ("PACKAGES LOADED")

PACKAGES LOADED


# SESSION

In [8]:
sess = tf.Session()
print ("OPEN SESSION")

OPEN SESSION


# TF CONSTANT

In [9]:
def print_tf(x):
    print("TYPE IS\n %s" % (type(x)))
    print("VALUE IS\n %s" % (x))
hello = tf.constant("HELLO. IT'S ME. ")
print_tf(hello)

TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("Const:0", shape=(), dtype=string)


# TO MAKE THINKS HAPPEN

In [10]:
hello_out = sess.run(hello)
print_tf(hello_out)

TYPE IS
 <class 'bytes'>
VALUE IS
 b"HELLO. IT'S ME. "


# OTHER TYPES OF CONSTANTS

In [11]:
a = tf.constant(1.5)
b = tf.constant(2.5)
print_tf(a)
print_tf(b)

TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("Const_1:0", shape=(), dtype=float32)
TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("Const_2:0", shape=(), dtype=float32)


In [12]:
a_out = sess.run(a)
b_out = sess.run(b)
print_tf(a_out)
print_tf(b_out)

TYPE IS
 <class 'numpy.float32'>
VALUE IS
 1.5
TYPE IS
 <class 'numpy.float32'>
VALUE IS
 2.5


# OPERATORS

In [13]:
a_plus_b = tf.add(a, b)
print_tf(a_plus_b)

TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("Add:0", shape=(), dtype=float32)


In [14]:
a_plus_b_out = sess.run(a_plus_b)
print_tf(a_plus_b_out)

TYPE IS
 <class 'numpy.float32'>
VALUE IS
 4.0


In [16]:
a_mul_b = tf.multiply(a, b)
a_mul_b_out = sess.run(a_mul_b)
print_tf(a_mul_b_out)

TYPE IS
 <class 'numpy.float32'>
VALUE IS
 3.75


# VARIABLES

In [17]:
weight = tf.Variable(tf.random_normal([5, 2], stddev=0.1))
print_tf(weight)

TYPE IS
 <class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
VALUE IS
 <tf.Variable 'Variable:0' shape=(5, 2) dtype=float32>


In [18]:
weight_out = sess.run(weight)
print_tf(weight_out)

FailedPreconditionError: Error while reading resource variable Variable from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/Variable)
	 [[node Variable/Read/ReadVariableOp (defined at <ipython-input-17-28f7757a1edf>:1) ]]

Original stack trace for 'Variable/Read/ReadVariableOp':
  File "d:\program\python_3_8_5\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\program\python_3_8_5\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "d:\program\python_3_8_5\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "d:\program\python_3_8_5\lib\site-packages\traitlets\config\application.py", line 837, in launch_instance
    app.start()
  File "d:\program\python_3_8_5\lib\site-packages\ipykernel\kernelapp.py", line 612, in start
    self.io_loop.start()
  File "d:\program\python_3_8_5\lib\site-packages\tornado\platform\asyncio.py", line 149, in start
    self.asyncio_loop.run_forever()
  File "d:\program\python_3_8_5\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "d:\program\python_3_8_5\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "d:\program\python_3_8_5\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "d:\program\python_3_8_5\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "d:\program\python_3_8_5\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "d:\program\python_3_8_5\lib\site-packages\tornado\gen.py", line 787, in inner
    self.run()
  File "d:\program\python_3_8_5\lib\site-packages\tornado\gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "d:\program\python_3_8_5\lib\site-packages\ipykernel\kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "d:\program\python_3_8_5\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "d:\program\python_3_8_5\lib\site-packages\ipykernel\kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "d:\program\python_3_8_5\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "d:\program\python_3_8_5\lib\site-packages\ipykernel\kernelbase.py", line 543, in execute_request
    self.do_execute(
  File "d:\program\python_3_8_5\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "d:\program\python_3_8_5\lib\site-packages\ipykernel\ipkernel.py", line 306, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "d:\program\python_3_8_5\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "d:\program\python_3_8_5\lib\site-packages\IPython\core\interactiveshell.py", line 2876, in run_cell
    result = self._run_cell(
  File "d:\program\python_3_8_5\lib\site-packages\IPython\core\interactiveshell.py", line 2922, in _run_cell
    return runner(coro)
  File "d:\program\python_3_8_5\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "d:\program\python_3_8_5\lib\site-packages\IPython\core\interactiveshell.py", line 3145, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "d:\program\python_3_8_5\lib\site-packages\IPython\core\interactiveshell.py", line 3337, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "d:\program\python_3_8_5\lib\site-packages\IPython\core\interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-17-28f7757a1edf>", line 1, in <module>
    weight = tf.Variable(tf.random_normal([5, 2], stddev=0.1))
  File "d:\program\python_3_8_5\lib\site-packages\tensorflow\python\ops\variables.py", line 260, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "d:\program\python_3_8_5\lib\site-packages\tensorflow\python\ops\variables.py", line 206, in _variable_v1_call
    return previous_getter(
  File "d:\program\python_3_8_5\lib\site-packages\tensorflow\python\ops\variables.py", line 199, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "d:\program\python_3_8_5\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2583, in default_variable_creator
    return resource_variable_ops.ResourceVariable(
  File "d:\program\python_3_8_5\lib\site-packages\tensorflow\python\ops\variables.py", line 264, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "d:\program\python_3_8_5\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1507, in __init__
    self._init_from_args(
  File "d:\program\python_3_8_5\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1701, in _init_from_args
    value = gen_resource_variable_ops.read_variable_op(handle, dtype)
  File "d:\program\python_3_8_5\lib\site-packages\tensorflow\python\ops\gen_resource_variable_ops.py", line 490, in read_variable_op
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "d:\program\python_3_8_5\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 742, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "d:\program\python_3_8_5\lib\site-packages\tensorflow\python\framework\ops.py", line 3477, in _create_op_internal
    ret = Operation(
  File "d:\program\python_3_8_5\lib\site-packages\tensorflow\python\framework\ops.py", line 1949, in __init__
    self._traceback = tf_stack.extract_stack()


# WHY DOES THIS ERROR OCCURS?

In [19]:
init = tf.initialize_all_variables()
sess.run(init)
print ("INITIALIZING ALL VARIALBES")

Instructions for updating:
Use `tf.global_variables_initializer` instead.
INITIALIZING ALL VARIALBES


# ONCE, WE INITIALIZE VARIABLES

In [20]:
weight_out = sess.run(weight)
print_tf(weight_out)

TYPE IS
 <class 'numpy.ndarray'>
VALUE IS
 [[ 0.0994032   0.05730625]
 [-0.01428521  0.00807735]
 [ 0.05131986 -0.12148719]
 [ 0.07857184 -0.04481057]
 [-0.12335142 -0.06314313]]


# PLACEHOLDERS

In [21]:
x = tf.placeholder(tf.float32, [None, 5])
print_tf(x)

TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("Placeholder:0", shape=(None, 5), dtype=float32)


## OPERATION WITH VARIABLES AND PLACEHOLDERS

In [22]:
oper = tf.matmul(x, weight)
print_tf(oper)

TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("MatMul:0", shape=(None, 2), dtype=float32)


In [23]:
data = np.random.rand(1, 5)
oper_out = sess.run(oper, feed_dict={x: data})
print_tf(oper_out)

TYPE IS
 <class 'numpy.ndarray'>
VALUE IS
 [[ 0.01903543 -0.05803744]]


In [24]:
data = np.random.rand(2, 5)
oper_out = sess.run(oper, feed_dict={x: data})
print_tf(oper_out)

TYPE IS
 <class 'numpy.ndarray'>
VALUE IS
 [[ 0.09006532 -0.14252055]
 [ 0.02876215 -0.17658558]]
